api:
  key: ""  # Set via BITUNIX_API_KEY env var
  secret: ""  # Set via BITUNIX_SECRET_KEY env var
  baseURL: "https://api.bitunix.com"
  wsURL: "wss://fapi.bitunix.com/public"

trading:
  symbols: ["BTCUSDT"]
  baseSizeRatio: 0.002
  maxPositionSize: 0.01
  maxDailyLoss: 0.05
  maxPriceDistance: 3.0
  dryRun: true  # Set to false for live trading

ml:
  modelPath: "models/model.onnx"  # Path relative to project root
  probThreshold: 0.65  # Minimum confidence for trade execution

features:
  vwapWindow: "30s"
  vwapSize: 600
  tickSize: 50

system:
  dataPath: "./data"  # Optional: for data persistence
  pingInterval: "15s"
  metricsPort: 8080
  restTimeout: "5s"
