# Example configuration file for bitunix-bot
# Copy this file to config.yaml and update with your values
# WARNING: Never commit your actual API keys to version control!

# API Configuration
# IMPORTANT: API keys must be set via environment variables:
# - BITUNIX_API_KEY
# - BITUNIX_SECRET_KEY
api:
  key: ""  # Set via BITUNIX_API_KEY env var
  secret: ""  # Set via BITUNIX_SECRET_KEY env var
  baseURL: "https://api.bitunix.com"
  wsURL: "wss://fapi.bitunix.com/public/"

# Trading Configuration
# WARNING: Live trading requires:
# 1. dryRun: false
# 2. FORCE_LIVE_TRADING=true environment variable
# 3. Valid API keys with trading permissions
trading:
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
  baseSizeRatio: 0.002
  maxPositionSize: 0.01      # 1% max position per symbol
  maxPositionExposure: 0.1   # 10% max total exposure per symbol
  maxDailyLoss: 0.05         # 5% max daily loss
  maxPriceDistance: 3.0      # 3 standard deviations max
  dryRun: true  # Set to false ONLY for live trading

# Symbol-specific configuration
symbolConfig:
  BTCUSDT:
    baseSizeRatio: 0.001
    maxPositionSize: 0.015
    maxPositionExposure: 0.15  # 15% max exposure for BTC
  ETHUSDT:
    baseSizeRatio: 0.002
    maxPositionSize: 0.01
    maxPositionExposure: 0.08  # 8% max exposure for ETH

# Technical Analysis Configuration
features:
  vwapWindow: "30s"
  vwapSize: 600
  tickSize: 50

# ML Configuration
ml:
  modelPath: "models/model.onnx"
  probThreshold: 0.65

# System Configuration  
system:
  dataPath: "C:\\DEV\\bitunixbot\\data"
  pingInterval: "15s"
  metricsPort: 8080
  restTimeout: "5s"
